### ISSUE TITLE
Cannot download fanfiction

### ISSUE THREAD

**Issue by MortalOP** [p0ody/ff2ebook#31] opened 2020-12-27 21:11 UTC
Shows output error in the new version and 'missing fic info' in old version.

**Comment by StarWolf3000** [comment] 2020-12-28 05:21
See #27 and #30.

**Comment by MortalOP** [comment] 2020-12-28 05:56
So is there any solution?

**Comment by StarWolf3000** [comment] 2020-12-28 08:16
There was a temporary solution with using a list of proxies, but it's rather difficult to circumvent the Cloudflare protection on FFN (it was introduced a few weeks ago, after they experienced a DDoS attack).

**Comment by MortalOP** [comment] 2020-12-28 20:46
I think only new fics are not downloadable because I can download old
ones......

**Comment by bastien8060** [comment] 2021-01-01 21:16
I think that would be because ff2ebooks can retrieve fanfic that has been downloaded before. Its "cached".

**Comment by bastien8060** [comment] 2021-01-01 21:17
If the maintainers of this repo (or anyone else) are interested, I am nearly finished working on a "fixed" version of this, that works on fanfiction.net, effectively bypassing CloudFlare for now. I could submit a pull/merge request when its done.

Edit: I am just stitching up a few details, before considering it finished :) !

Edit 2: I can confirm it works well too, just rather slow.

**Comment by PenguinPaws** [comment] 2021-01-02 01:01
> I think that would be because ff2ebooks can retrieve fanfic that has been downloaded before. Its "cached".

ff2ebook definitely does archive previously pulled stories. That's where there's an [Archive](http://www.ff2ebook.com/archive.php) link at the top :)

**Comment by bastien8060** [comment] 2021-01-02 11:50
Yep :) My fix works well so far but its pretty slow. I would only use it on small fanfic. I will keep working on this tomorrow to see if I can improve the speed :)

Edit: And there is also the pairing detections to fix.
![Screenshot_2021-01-02-11-44-27-459_com android chrome](https://user-images.githubusercontent.com/26277763/103456686-798bd000-4cf0-11eb-8c10-71ef5d59afee.jpg)

**Comment by LanzCorporalAssWipe** [comment] 2021-01-02 16:01
> Yep :) My fix works well so far but its pretty slow. I would only use it on small fanfic. I will keep working on this tomorrow to see if I can improve the speed :)
> 
> Edit: And there is also the pairing detections to fix.
> ![Screenshot_2021-01-02-11-44-27-459_com android chrome](https://user-images.githubusercontent.com/26277763/103456686-798bd000-4cf0-11eb-8c10-71ef5d59afee.jpg)

Bro. If you manage to get it working i will proclaim you as the Omnissiah.

**Comment by p0ody** [comment] 2021-01-02 16:45
@bastien8060 , your work is appreciated.  Just add a pull request when you're satisfied with your work and I'll merge it.

Personally i dont have the time anymore to work on this.

Thank you

**Comment by bastien8060** [comment] 2021-01-03 20:02
> @bastien8060 , your work is appreciated. Just add a pull request when you're satisfied with your work and I'll merge it.
> 
> Personally i dont have the time anymore to work on this.
> 
> Thank you

Glad it helps.
I can submit a merge request for now with some slow execution time if your willing to level up your server's timeout value :). You probably will need to put it up to 5 minutes or so, for people converting large ebooks (around ~40 chapters ish), when ajax calls are stacked up, since php is not asynchronous among different clients.

It will take some time before I find some quality and reliable proxies. I have about 140 proxies I think, but only 50 of them are not "that slow". Also 10 of them are really fast but will run out after 5GB (Not an issue for now I think).

Edit: I only applied edits to the portable branch since I don't have time to get a database. 

here (https://github.com/bastien8060/ff2ebook) if you want to have a look

**Comment by StarWolf3000** [comment] 2021-01-03 20:25
> 
> Also 10 of them are really fast but will run out after 5GB (Not an issue for now I think).
> 

Is that a daily limitation?

**Comment by bastien8060** [comment] 2021-01-04 10:50
> > Also 10 of them are really fast but will run out after 5GB (Not an issue for now I think).
> 
> Is that a daily limitation?

Ahem, monthly... But the rest of them are unlimited. I'm not too worried with that just yet. There are many other proxies still and I am still trying to find more.

**Comment by bastien8060** [comment] 2021-01-04 18:17
Alright It's finished, now waiting on moderator to merge the code. FF2ebook.com won't be fixed until the moderator of that website (probably @p0ody, but not necessarily) chooses to update it with latest changes from this GitHub Repo. If all goes well, everything should be working soon. 

Btw, don't expect it to be lightning-fast like before. I'm still surprised with how fast it used to be (lol). Also, there is a very slight error rate, but it does happen. You can try again in that case or run it on your own pc, with a VM. (probably wont need to go that far.) 

If you want to see the details, I encourage you to check #33.

> Bro. If you manage to get it working i will proclaim you as the Omnissiah.

All credit for the tool of course remains to @p0ody. FF2Ebook is a very well coded tool and website, and he's the one to write it all in the first place. I only just wrote a small fix.

**Edit:** I quite like working on this project too btw, and I am a huge fan of this repo. I could add another fanfiction site to be supported, in my spare time tomorrow if you guys have any ideas. (I thought Wattpad because I would be using it). 

How does that sound?

**Edit 2:** I almost feel like I'm writing an A/N lol.

**Closed as completed** 2021-09-26 18:21 UTC
